# Generated by Django 2.1.2 on 2019-02-26 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0002_auto_20190226_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_commodity_ammount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wish_commodity_ammount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=50)),
                ('time_of_creation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('own_commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_commodity', to='Exchange.Commodity')),
                ('wish_commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_commodity', to='Exchange.Commodity')),
            ],
        ),
    ]
